claudio:
  amazonia:
    region:
      static: us-east-2
      auto: false
    crediario:
      cadeado: AKI|AT|CKAT3|H6QQ|35XXL3
      todomundo-sabe: IxuF0x|uWXmPPJuQH4pfez|Xm8JeO|JfIHc|d1pM8CzK
    ponto-final:
      uris: ht|tp|s://sqs.us-ea|st-2.amazonaw|s.c|om/21112578|7133/pagamento


spring:
  datasource:
    url: jdbc:postgresql://prato-pronto.c5iicuok4ddw.us-east-2.rds.amazonaws.com:5432/prato_pronto
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true